### ISSUE TITLE
Support buffered file read

### ISSUE THREAD

**Issue by akshaybabloo** [vschwaberow/genhash#6]
Could you add support for buffered file hashing? Currently only string can be used

This is what I am using:

```go
func hashFunction(filePath string) (string, string, error) {
	file, err := os.Open(filePath)
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	hash := sha256.New()
	defer hash.Reset()
	
	if _, err := io.Copy(hash, file); err != nil {
		return "", "", err
	}

	return hex.EncodeToString(hash.Sum(nil)), filePath, nil
}
```

**Comment by vschwaberow** [comment]
I implemented this functionality a while ago in my Rust based hashing tool: https://github.com/vschwaberow/rustgenhash

If you would like this functionality in this Go repository I am open for your Pull Request.
